[web]
192.187.56.3                                                                                                          

[localhost]
 localhost

 [localhost:vars]
 Course="DevOps From inventory"
 Trainer="Divyakrishna"
 Duration="Lifelong"
 PERSON= "Divya from inventory"
 WISHES= "Night from inventory"