[web]
192.187.56.3                                                                                                          

[localhost]
 localhost

 [localhost:vars]
 course="DevOps From inventory"
 Trainer="Divyakrishna"
 Duration="Lifelong"